# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(361, 279)
        MainWindow.setMinimumSize(QtCore.QSize(361, 279))
        MainWindow.setMaximumSize(QtCore.QSize(361, 279))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("font: 11pt \"Noto Serif CJK KR\";\n"
"background-color: rgb(98, 160, 234);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chiste = QtWidgets.QPushButton(self.centralwidget)
        self.chiste.setGeometry(QtCore.QRect(80, 240, 111, 21))
        self.chiste.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.chiste.setToolTipDuration(9)
        self.chiste.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.chiste.setObjectName("chiste")
        self.traducir = QtWidgets.QPushButton(self.centralwidget)
        self.traducir.setGeometry(QtCore.QRect(200, 240, 81, 21))
        self.traducir.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.traducir.setToolTipDuration(9)
        self.traducir.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.traducir.setObjectName("traducir")
        self.esBtn = QtWidgets.QPushButton(self.centralwidget)
        self.esBtn.setGeometry(QtCore.QRect(290, 160, 31, 31))
        self.esBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.esBtn.setToolTipDuration(9)
        self.esBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"image: url(:/Bandera/Bandera-de-Reino-Unido.png);\n"
"\n"
"")
        self.esBtn.setText("")
        self.esBtn.setObjectName("esBtn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 60, 301, 131))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 191, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(240, 20, 21, 25))
        self.searchBtn.setStyleSheet("image: url(:/Busqueda/lupa.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.searchBtn.setText("")
        self.searchBtn.setObjectName("searchBtn")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 200, 141, 25))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(300, 10, 51, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("image: url(:/Busqueda/informationwebcircularbuttonsymbol_79860.png);\n"
"border-radius: 10px;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("image: url(:/Busqueda/historique-icone-de-l-historique-noir.png);\n"
"border-radius: 10px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.chiste.raise_()
        self.traducir.raise_()
        self.textBrowser.raise_()
        self.lineEdit.raise_()
        self.searchBtn.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.esBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JokeApp"))
        self.chiste.setText(_translate("MainWindow", "Contar chiste"))
        self.traducir.setText(_translate("MainWindow", "Traducir"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Buscar por palabra"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Misc"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Programación"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Navidad"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Oscuro"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Escalofriante"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Cualquiera"))
import imagenes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
